import { IVideoCardDataModules } from "../modules/IVideoCardDataModules";

export let videoCardDataList:IVideoCardDataModules[] = [
  {
    img: 'https://i1.hdslb.com/bfs/archive/97b197ce785ac84bf160d7583875b0f8fe1753cc.jpg',
    viewCounts: '',
    commentsCounts: '',
    duration: '28:25',
    title: '去了一趟挪威。',
    author: '影视飓风'
  },
  {
    img: 'https://i0.hdslb.com/bfs/archive/dd0d23c81dad8d58ca3f05bb0200239d2a7c4a99.jpg',
    viewCounts: '9032',
    commentsCounts: '120',
    duration: '40:33',
    title: '你阿玛我说过，你在京城连龙根儿都留不住',
    author: '世子大柿子'
  },
  {
    img: 'https://i2.hdslb.com/bfs/archive/ed68722b93e77839f1c161204dabcbbd3767eb5d.jpg',
    viewCounts: '2131',
    commentsCounts: '232',
    duration: '01:51:16',
    title: '万字爆肝，120分钟讲透《置身事内》，理解中国经济的底层逻辑',
    author: '大罗小罗自习室'
  },
  {
    img: 'https://i0.hdslb.com/bfs/archive/7412e36d5853b9b2066c53744f163b311279450d.jpg',
    viewCounts: '4359',
    commentsCounts: '6464',
    duration: '05:43',
    title: '播完才敢说…穿搭真没什么好捧的…',
    author: '大沛沛沛吖'
  },
  {
    img: 'https://i1.hdslb.com/bfs/archive/6d7a68379cb01d7fd0e153b2d2c6cf026cc60132.jpg',
    viewCounts: '25588',
    commentsCounts: '123',
    duration: '08:25',
    title: '一边是天堂，一边是地狱，菲律宾贫富差距到底有多夸张？太魔幻了。',
    author: '20岁了还没去过星巴克'
  },
  {
    img: 'https://i1.hdslb.com/bfs/archive/88e4cd80a2d820db17e7775af0c4621a1d66dd87.jpg',
    viewCounts: '6360',
    commentsCounts: '341',
    duration: '01:41',
    title: '《猫是怎么分辨主人的》',
    author: '十四毅'
  },
  {
    img: 'https://i0.hdslb.com/bfs/archive/ff395cf2ac1655bcb06b3a5d42cd6def775a732e.jpg',
    viewCounts: '1232',
    commentsCounts: '720',
    duration: '12:33',
    title: '评论区太多人问的《疯狂动物城2》定档预告来了！',
    author: '迪士尼影业'
  },
  {
    img: 'https://i0.hdslb.com/bfs/archive/ef8136dab094fccc55e7ee2074827631d42a3156.jpg',
    viewCounts: '1029',
    commentsCounts: '721',
    duration: '12:33',
    title: '台湾省普通人的生活水平究竟如何；在大陆多少月薪，可以过上台湾省普通人的生活',
    author: '多明海'
  }
]